// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK2yGekFGdCZqdZY6UaqifFxvbqmxYvJc',
    appId: '1:883341278564:web:71dd8732fafc1770300e71',
    messagingSenderId: '883341278564',
    projectId: 'photosaver-8be19',
    authDomain: 'photosaver-8be19.firebaseapp.com',
    storageBucket: 'photosaver-8be19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbyr8KDnaJCFRtnFJNtNQc4v3Vl9PUbg0',
    appId: '1:883341278564:android:c9e189426ba33a5d300e71',
    messagingSenderId: '883341278564',
    projectId: 'photosaver-8be19',
    storageBucket: 'photosaver-8be19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Rs1xuY2U58AoANMXf6QPEWSDoaxpY6s',
    appId: '1:883341278564:ios:54687b6ed61975f2300e71',
    messagingSenderId: '883341278564',
    projectId: 'photosaver-8be19',
    storageBucket: 'photosaver-8be19.appspot.com',
    iosBundleId: 'com.example.photosaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Rs1xuY2U58AoANMXf6QPEWSDoaxpY6s',
    appId: '1:883341278564:ios:75ea4a4409b2eb44300e71',
    messagingSenderId: '883341278564',
    projectId: 'photosaver-8be19',
    storageBucket: 'photosaver-8be19.appspot.com',
    iosBundleId: 'com.example.photosaver.RunnerTests',
  );
}
